name: neonbreaker_pro
description: NeonBreaker Pro - Professional Neon Brick Breaker
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

# --------------------------------------------------
# Android launcher icon configuration
# --------------------------------------------------
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/neonbreaker_icon.png"
  adaptive_icon_background: "#05020D"
  adaptive_icon_foreground: "assets/icon/neonbreaker_icon.png"
  min_sdk_android: 21
